services:
  virarith_app:
    image: node:22-alpine
    ports:
      - '3000:3000'
    volumes:
      - ./build:/app
      - ./package.json:/app/package.json
    command: sh -c "npm install && node index.js"
    working_dir: /app
    depends_on:
      - postgres
      - minio
    environment:
      BETTER_AUTH_URL: ${PUBLIC_BETTER_AUTH_URL}

      PRIVATE_MINIO_ENDPOINT: ${PRIVATE_MINIO_ENDPOINT}
      PUBLIC_MINIO_ENDPOINT: ${PUBLIC_MINIO_ENDPOINT}
      PRIVATE_MINIO_PORT: ${PRIVATE_MINIO_PORT}

      PRIVATE_BUCKET_ACCESS_KEY: ${PRIVATE_BUCKET_ACCESS_KEY}
      PRIVATE_BUCKET_SECRET_KEY: ${PRIVATE_BUCKET_SECRET_KEY}

      PRIVATE_POSTGRES_USER: ${PRIVATE_POSTGRES_USER}
      PRIVATE_POSTGRES_PASSWORD: ${PRIVATE_POSTGRES_PASSWORD}
      PRIVATE_POSTGRES_URL: ${PRIVATE_POSTGRES_URL} # This is 'postgres:5432'
      PRIVATE_POSTGRES_DB: ${PRIVATE_POSTGRES_DB}
    networks:
      - virarith
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    depends_on:
      - postgres
    networks:
      - virarith

  postgres:
    image: postgres:latest
    container_name: virarith-postgres
    restart: always
    environment:
      POSTGRES_USER: ${PRIVATE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PRIVATE_POSTGRES_PASSWORD}
      POSTGRES_DB: ${PRIVATE_POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - virarith
  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z-cpuv1
    container_name: virarith-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - '9000:9000' # S3 API
      - '9001:9001' # MinIO web UI
    volumes:
      - minio_data:/data
    networks:
      - virarith

  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80' # HTTP from host to Nginx
      - '443:443' # HTTPS from host to Nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - virarith_app
      - minio
      - pgadmin
      - postgres
    networks:
      - virarith
    restart: always
volumes:
  postgres_data:
  minio_data:

networks:
  virarith:
